-- ACEQSA - Modelo base de inventario (MySQL 8+)
CREATE DATABASE IF NOT EXISTS aceqsa_inventory CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE aceqsa_inventory;
CREATE TABLE categorias (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, nombre VARCHAR(100) NOT NULL UNIQUE, tipo ENUM('PRODUCTO','SERVICIO') NOT NULL DEFAULT 'PRODUCTO', activo BOOLEAN NOT NULL DEFAULT TRUE, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE proveedores (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, nombre VARCHAR(160) NOT NULL, identificacion VARCHAR(60), email VARCHAR(160), telefono VARCHAR(40), pais VARCHAR(80), activo BOOLEAN DEFAULT TRUE, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE productos (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, sku VARCHAR(60) NOT NULL UNIQUE, categoria_id BIGINT UNSIGNED NOT NULL, nombre VARCHAR(180) NOT NULL, descripcion TEXT, marca VARCHAR(100), modelo VARCHAR(100), costo DECIMAL(14,2) NOT NULL DEFAULT 0, precio DECIMAL(14,2) NOT NULL DEFAULT 0, impuesto_pct DECIMAL(5,2) NOT NULL DEFAULT 13.00, stock_minimo INT NOT NULL DEFAULT 0, activo BOOLEAN NOT NULL DEFAULT TRUE, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, FOREIGN KEY (categoria_id) REFERENCES categorias(id));
CREATE TABLE bodegas (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, nombre VARCHAR(120) NOT NULL, ubicacion VARCHAR(220), activo BOOLEAN DEFAULT TRUE);
CREATE TABLE existencias (producto_id BIGINT UNSIGNED NOT NULL, bodega_id BIGINT UNSIGNED NOT NULL, cantidad INT NOT NULL DEFAULT 0, reservado INT NOT NULL DEFAULT 0, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, PRIMARY KEY(producto_id,bodega_id), FOREIGN KEY(producto_id) REFERENCES productos(id), FOREIGN KEY(bodega_id) REFERENCES bodegas(id), CHECK(cantidad>=0), CHECK(reservado>=0 AND reservado<=cantidad));
CREATE TABLE movimientos_inventario (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, producto_id BIGINT UNSIGNED NOT NULL, bodega_id BIGINT UNSIGNED NOT NULL, tipo ENUM('ENTRADA','SALIDA','AJUSTE_POSITIVO','AJUSTE_NEGATIVO','RESERVA','LIBERACION') NOT NULL, cantidad INT NOT NULL, referencia VARCHAR(100), observacion VARCHAR(500), usuario VARCHAR(120), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(producto_id) REFERENCES productos(id), FOREIGN KEY(bodega_id) REFERENCES bodegas(id), CHECK(cantidad>0), INDEX idx_mov_producto_fecha(producto_id,created_at));
CREATE TABLE compras (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, proveedor_id BIGINT UNSIGNED NOT NULL, numero_documento VARCHAR(80), fecha DATE NOT NULL, estado ENUM('BORRADOR','RECIBIDA','ANULADA') DEFAULT 'BORRADOR', total DECIMAL(14,2) DEFAULT 0, FOREIGN KEY(proveedor_id) REFERENCES proveedores(id));
CREATE TABLE compra_detalle (compra_id BIGINT UNSIGNED NOT NULL, producto_id BIGINT UNSIGNED NOT NULL, cantidad INT NOT NULL, costo_unitario DECIMAL(14,2) NOT NULL, PRIMARY KEY(compra_id,producto_id), FOREIGN KEY(compra_id) REFERENCES compras(id), FOREIGN KEY(producto_id) REFERENCES productos(id));
CREATE VIEW vw_stock_disponible AS SELECT p.sku,p.nombre,b.nombre bodega,e.cantidad,e.reservado,(e.cantidad-e.reservado) disponible,p.stock_minimo FROM existencias e JOIN productos p ON p.id=e.producto_id JOIN bodegas b ON b.id=e.bodega_id;
CREATE VIEW vw_reposicion AS SELECT p.sku,p.nombre,SUM(e.cantidad-e.reservado) disponible,p.stock_minimo FROM productos p LEFT JOIN existencias e ON e.producto_id=p.id WHERE p.activo=TRUE GROUP BY p.id HAVING disponible<=p.stock_minimo;
